### ISSUE TITLE
Migration methods (:create_view, :update_view, ...) signature mismatch with the scenic gem

### ISSUE THREAD

**Issue by dreig** [EmpaticoOrg/scenic-mysql_adapter#12]
**EDIT:** I was wrong. There may be some issues in my own code.
**EDIT 2:** There is an issue with how `invert_create_view`, and there is a corresponding https://github.com/scenic-views/scenic/issues/286 in the `scenic` repo

The migration methods (`create_view`, `update_view`,...) in the scenic gem use keyword arguments for specifying the `sql_definition` and `version` [see here](https://github.com/scenic-views/scenic/blob/048e08057e0bd76a700e7759344000cdc4e78235/lib/scenic/statements.rb#L25), while this gem uses [two positional parameters](https://github.com/EmpaticoOrg/scenic-mysql_adapter/blob/d0ce1bd226ca17dfbca2f89dd9eec552eacce148/lib/scenic/adapters/my_sql.rb#L29)

This currently leads to errors when running `rails db:rollback` as it attempts to generate an inverse migration for `create_view`, and fails because the scenic gem expects the optional arguments to be a hash: [see here](https://github.com/scenic-views/scenic/blob/048e08057e0bd76a700e7759344000cdc4e78235/lib/scenic/command_recorder.rb#L23)
I will solve this issue for myself by explicitly writing both the up and down versions of the migration.

But, I think this gem should conform to the method signatures expected by the scenic gem.

**Comment by cainlevy** [comment]
@dreig It's quite possible for this MySQL adapter to drift out of date from scenic upstream. Thanks for raising the issue.

I'm currently able to look at pull requests, but I'm not actively maintaining compatibility as my current project did not choose Ruby/MySQL.
